= Аннотация


== Перечень эксплуатационной документации

. _{em}_. Руководство администратора.
. _{em}_. Руководство пользователя.
. _{em}_. Руководство разработчика.
. _{em}_. Описание полей карточек модуля.


== Назначение и функции Модуля

_{em}_ является дополнительным модулем Docsvision, который обеспечивает возможность обмена электронными документами с контрагентами через системы операторов ЭДО (электронного документооборота).

[NOTE]
====
[.note__title]#Note:# Оператор ЭДО – организация, предоставляющая услуги по обмену открытой и конфиденциальной информацией по телекоммуникационным каналам связи в рамках электронного документооборота.

Под [.dfn .term]_электронным документом_ здесь и далее подразумеваются формализованные и неформализованные юридически значимые электронные документы (если не указан определенный тип [.dfn .term]_электронного документа_).
====

Модуль предоставляет следующие возможности:

* отправка электронных документов:
** формализованные: УПД (https://www.diadoc.ru/docs/upd[универсальный передаточный документ]), Счет-фактура, Акт, Накладная, Универсальный корректировочный документ (УКД), Исправление УПД, Корректировочный счет-фактура (КСФ) и Исправление счета-фактуры (ИСФ);
** неформализованные;
* получение электронных документов:
** формализованные: УПД, Счет-фактура, Акт, Накладная, УКД, Исправление УПД, КСФ и ИСФ;
** неформализованные: Акт, Акт сверки, Детализация, Договор, Доверенность, Доп. соглашение к договору, Накладная, Неформализованный, Протокол согласования цены, Реестр сертификатов, Счет, Ценовой лист;
* создание запросов на аннулирование документов, формирование ответов на запросы об аннулировании;
* создание запросов на уточнение, получение уточнений (корректировок и исправлений) по документам;
* загрузка подтверждения оператора ЭДО о получении титула продавца (с отправкой извещения о получении);
* электронный обмен через одного или нескольких операторов ЭДОlink:#fntarg_1[^1^];
* загрузка информации о контрагентах и подразделениях организации из системы оператора ЭДО;
* настройка получения, отправки и создания документов в системе Docsvision с помощью Справочника настроек операторов ЭДО, возможность разработки компонентов, реализующих указанные функции.

*Обратите внимание*:

. В списке поддерживаемых типов электронных документов приведены все типы поддерживаемые Модулем. Фактическая возможность обмена определенными типами документов зависит от поддержки работы с данными типами оператором ЭДО.
. Все перечисленные возможности предоставляются только после установки коннектора к оператору ЭДО, с которым осуществляется взаимодействие. Если коннекторы не установлены, обмен электронными документами будет невозможен.

link:#fnsrc_1[^1^] Для работы с оператором ЭДО требуется коннектор к данному оператору (устанавливается отдельно).
