= Необходимые ресурсы

== Необходимое техническое обеспечение

Специальные требования к аппаратному обеспечению не предъявляются.

== Необходимое программное обеспечение

=== Требования серверной части Приложения

Модули Docsvision::
. Серверная часть модуля "Платформа" версии 5.5.1 сборка 3291 и выше.
. Серверная часть модуля "Базовые объекты" версии 5.5.2 версии 4236 и выше.
. Серверная часть приложения "Управление документами" версии 5.5.2 сборка 4234 и выше.
. Серверная часть модуля "Управление процессами" версии 5.5.1 сборка 3163 и выше.
. Серверная часть модуля "Конструктор согласований" версии 5.5.1 сборка 3185 и выше.
. Серверная часть приложения "Делопроизводство 4.5" версии 5.5.1 сборка 3161 и выше.
. Серверная часть модуля "Windows-клиент" версии 5.5.1 сборка 3206 и выше.

СКЗИ "КриптоПро CSP"::
СКЗИ "КриптоПро CSP" должно быть установлено на клиентах и сервере/серверах СУБП (Workflow). Полные требования к компонентам КриптоПро и их версиям приведены в документе "Система управления документами и бизнес-процессами Docsvision. Руководство по установке и администрированию".

=== Требования клиентской части Приложения

Модули Docsvision::
. Клиентская часть модуля "Платформа" версии 5.5.1 сборка 3291 и выше.
. Клиентская часть модуля "Базовые объекты" версии 5.5.2 версии 4236 и выше.
. Клиентская часть приложения "Управление документами" версии 5.5.2 сборка 4234 и выше.
. Клиентская часть модуля "Управление процессами" версии 5.5.1 сборка 3163 и выше.
. Клиентская часть модуля "Конструктор согласований" версии 5.5.1 сборка 3185 и выше.
. Клиентская часть приложения "Делопроизводство 4.5" версии 5.5.1 сборка 3161 и выше.
. Клиентская часть модуля "Windows-клиент" версии 5.5.1 сборка 3206 и выше.

СКЗИ "КриптоПро CSP"::
(см. требования в документе "Система управления документами и бизнес-процессами Docsvision. Руководство по установке и администрированию").

== Лицензия

Для работы с модулем _{em}_ лицензия на систему Docsvision должна содержать дополнительную опцию _{em}_.

