= IDocumentDataReader -- интерфейс

Интерфейс `IDocumentDataReader` определяет методы, которые должен реализовывать xref:card-data-reading.adoc[компонент чтения данных карточки].

* *Пространство имен:* `DocsVision.Edi.Interfaces`
* *Сборка:* `DocsVision.Edi.Interfaces.dll`

== Синтаксис

[source,csharp]
----
public interface IDocumentDataReader
----

== Методы

[cols=",",options="header"]
|===
|Имя |Описание

|`GetActualSignatures(Guid)`
a|Возвращает актуальные подписи (действительные с действующим сертификатом) карточки.

Тип возвращаемого значения: `ItemCollection<xref:api/DocumentSignature.adoc[DocumentSignature]>`

.Параметры:
* `cardId` -- идентификатор карточки, подписи которой возвращаются.

В стандартной конфигурации модуля метод вызывается при открытии формы отправки электронного документа.

|`GetAllFiles(Guid)`
a|Возвращает основные и дополнительные файлы карточки.

Тип возвращаемого значения: `ItemCollection<xref:api/DocumentFileData.adoc[DocumentFileData]>`

.Параметры:
* `cardId` -- идентификатор карточки, файлы которой возвращаются.

В стандартной конфигурации модуля метод вызывается при отправке электронного документа.

|`GetAllRecipients(Guid)`
a|Возвращает список получателей электронного документа.

Тип возвращаемого значения: `ItemCollection<xref:api/DocumentRecipientData.adoc[DocumentRecipientData]>`.

.Параметры:
* `cardId` -- идентификатор карточки, из которой запрашиваются получатели.

В стандартной конфигурации модуля метод вызывается при отправке электронного документа.

|`GetDigest(Guid)`
a|Предоставляет описание (дайджест) карточки.

*Тип возвращаемого значения*: `String`.

.Параметры:
* `cardId` -- идентификатор карточки.

В стандартной конфигурации модуля метод вызывается при открытии формы отправки электронного документа.

|`GetFileContent(Guid, Guid)`
a|Предоставляет содержимое файла карточки.

*Тип возвращаемого значения*: `System.String`.

.Параметры:
* `cardId` -- идентификатор карточки.
* `fileId` -- идентификатор файла, для которого возвращается содержимое.

В стандартной конфигурации модуля метод вызывается при открытии формы отправки электронного документа.

|`GetFileDigest(Guid, Guid)`
a|Предоставляет описание (дайджест) файла карточки.

*Тип возвращаемого значения*: `System.String`.

.Параметры:
* `cardId` -- идентификатор карточки.
* `fileId` -- идентификатор файла, для которого возвращается описание.

В стандартной конфигурации модуля метод вызывается при открытии формы отправки электронного документа.

|`GetInvoiceReplyData(Guid)`
a|Возвращает строку с ответом на сообщение, полученное от оператора ЭДО.

Тип возвращаемого значения: `System.String`.

.Параметры:
* `cardId` -- идентификатор карточки.

В стандартной конфигурации модуля метод вызывается при формировании ответной подписи.

Метод `GetInvoiceReplyData` должен вернуть строку с данными карточки в определенном формате, который ожидается методом `IMessageService.GenerateInvoiceReply` коннектора к оператору ЭДО. В реализации коннектора к Диадок для ответа по УПД метод `GetInvoiceReplyData` должен вернуть сериализованный объект `DocsVision.Edi.Entities.BuyerReplyData`, заполненный данными карточки УПД, по которой формируется ответ.

|`GetLastSignedFiles(Guid)`
a|Возвращает последние (по времени) подписанные файлы карточки.

*Тип возвращаемого значения*: `ItemCollection<xref:api/DocumentFileData.adoc[DocumentFileData]>`.

.Параметры:
* `cardId` -- идентификатор карточки.

|`GetPrintFormContent(Guid)`
a|Возвращает содержимое карточки, подготовленное для печати.

*Тип возвращаемого значения*: `String`.

.Параметры:
* `cardId` -- идентификатор карточки.

В стандартной конфигурации модуля метод вызывается печати УПД.

|`GetReplyFileComment(Guid, Guid, MessageFileType)`
a|Формирует строку с комментарием к файлу отправленного электронного сообщения.

*Тип возвращаемого значения*: `System.String`.

.Параметры:
* `cardId` -- идентификатор карточки.
* `fileId` -- идентификатор файла, для которого нужен комментарий.
* `fileType` -- ответ контрагента на переданный в электронном сообщении файл.

В стандартной конфигурации модуля метод вызывается при формировании сообщений для журнала обмена ЮЗДО.

|`GetReplyFileDigest(Guid, Guid, MessageFileType)`
a|Формирует строку с дайджестом файла отправленного электронного сообщения.

*Тип возвращаемого значения*: `System.String`.

.Параметры:
* `cardId` -- идентификатор карточки.
* `fileId` -- идентификатор файла, для которого нужен дайджест.
* `fileType` -- ответ контрагента на переданный в электронном сообщении файл.

В стандартной конфигурации модуля метод вызывается при формировании сообщений для журнала обмена ЮЗДО.

|`GetSignedFiles(Guid, Guid)`
a|Возвращает файлы карточки, которые подписаны указанной подписью.

*Тип возвращаемого значения*: `ItemCollection<xref:api/DocumentFileData.adoc[DocumentFileData]>`.

.Параметры:
* `cardId` -- идентификатор карточки.
* `signatureGroupId` -- идентификатор ЭЦП.

В стандартной конфигурации модуля метод вызывается при открытии формы отправки электронного документа.

|`Initialize(ObjectContext)`
a|Инициализирует экземпляр компонента отправки электронного документа.

.Параметры:
* `objectContext` -- контекст объектов.

|`PrepareFileData(Guid, Guid, Guid, Boolean, String)`
a|Создаёт экземпляр файла сообщения электронного обмена.

*Тип возвращаемого значения*: `xref:api/MessageFile.adoc[MessageFile]`.

.Параметры:
* `cardId` -- идентификатор карточки, содержащий файл.
* `fileId` -- идентификатор файла, передаваемого в сообщении.
* `signatureId` -- идентификатор подписи, которой подписан файл.
* `isMain` -- файл является основным.
* `tempFolder` -- временный каталог, для выгрузки файла.

В стандартной конфигурации модуля метод вызывается при отправке оператору ЭДО сообщения электронного обмена с новым документом.

В большинстве случаев полностью реализовывать данный метод не требуется, т.к. принцип подготовки файла электронного сообщения стандартный. Чтобы использовать стандартный механизм формирования, достаточно вернуть из метода значение `null`.

|`PrepareMessageData(Guid, String, String)`
a|Создаёт экземпляр электронного сообщения электронного обмена.

*Тип возвращаемого значения*: `xref:api/MessageData.adoc[MessageData]`.

.Параметры:
* `cardId` -- идентификатор карточки, для которой формируется сообщение электронного обмена для отправки оператору ЭДО.
* `documentType` -- тип документа.
* `documentVersion` -- версия документа.

В стандартной конфигурации модуля метод вызывается при отправке оператору ЭДО сообщения электронного обмена с новым документом.

|`ValidateSignature(Guid, Guid, Guid)`
a|Проверяет подпись файла и возвращает объект, содержащий результаты проверки.

Тип возвращаемого значения: `xref:api/SignatureValidation.adoc[SignatureValidation]`

.Параметры:
* `cardId` -- идентификатор карточки с проверяемым файлом.
* `fileId` -- идентификатор файла карточки, подпись которого проверяется.
* `signatureId` -- идентификатор подписи.

В стандартной конфигурации модуля метод вызывается при работе с Журналом обмена ЮЗДО, если в процессе обмена УПД от контрагента поступили подписанные файлы.
|===
