= IDocumentCreator -- интерфейс

Интерфейс `IDocumentCreator` определяет методы, которые должен реализовывать компонент xref:doc-creating.adoc[создания документов].

* *Пространство имен:* `DocsVision.Edi.Interfaces`
* *Сборка:* `DocsVision.Edi.Interfaces.dll`

== Синтаксис

[source,csharp]
----
public interface IDocumentCreator
----

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание

|`AddReplyFilesToDocument(MessageData, Guid)`
a|Переносит файлы из электронного сообщения в целевую карточку.

.Параметры:
* `messageData` -- электронное сообщение, полученное от контрагента
* `partnerId` -- идентификатор контрагента (в Справочнике сотрудников), от которого получено сообщение

В стандартной конфигурации модуля метод вызывается бизнес-процессом "Перенос файлов из сообщений ЮЗДО".

|`CreateDocument(MessageData, Guid, Guid)`
a|Создаёт новую карточку по полученному от оператору ЭДО сообщению. Если карточка успешно создана, возвращает `True`.

Тип возвращаемого значения: `Boolean`

.Параметры:
* `messageData` -- сообщение от оператора ЭДО с типом xref:api/MessageData.adoc[MessageData].
* `partnerId` -- идентификатор отправившего электронный документ контрагента в системе {dv}.
* `partnerDepartmentId` -- идентификатор подразделения контрагента, если электронный документ отправлен подразделением контрагента.

В стандартной конфигурации модуля метод вызывается, когда поступил новый электронный документ.

|`Initialize(ObjectContext, Guid)`
a|Инициализирует экземпляр компонента создания документов.

.Параметры:
* `objectContext` -- контекст объектов.
* `defaultKindId` -- идентификатор вида создаваемого документа.
|===
