= IMessageService -- интерфейс

Интерфейс `IMessageService` определяет методы, которые должен реализовывать компонент xref:message-service.adoc[сервиса сообщений].

* *Пространство имен:* `DocsVision.Edi.Interfaces`
* *Сборка:* `DocsVision.Edi.Interfaces.dll`

== Синтаксис

[source,csharp]
----
public interface IMessageService
----

== Методы

[cols=",",options="header"]
|===
|Имя |Описание

|`EventExists(String, String)`
a|Проверяет наличие события с указанным идентификатором в ящике организации. Возвращает True, если событие есть.

*Тип возвращаемого значения*: `Boolean`.

.Параметры:
* boxId -- идентификатор ящика организации.
* eventId -- идентификатор события.

В стандартной конфигурации модуля метод вызывается при получении новых сообщений от оператора ЭДО.

|`GenerateCorrectionRequest(String, String, String, X509Certificate2, String, String)`
a|Формирует запрос на уточнение.

*Тип возвращаемого значения*: `xref:api/MessageFile.adoc[MessageFile]`.

.Параметры:
* `boxId` -- идентификатор ящика организации.
* `messageId` -- идентификатор сообщения у оператора обмена.
* `entityId` -- идентификатор сущности у оператора ЭДО, по которому отправляется запрос на уточнение.
* `certificate` -- сертификат, которым подписывается запрос.
* `positionName` -- должность подписывающего запрос сотрудника.
* `comment` -- комментарий к запросу.

В стандартной конфигурации модуля метод вызывается, когда пользователь запрашивает уточнение по поступившему документу.

|`GenerateInvoiceReceipt(String, String, String, X509Certificate2, String)`
a|Формирует ответную подпись на полученный документ.

*Тип возвращаемого значения*: `xref:api/MessageFile.adoc[MessageFile]`.

.Параметры:
* `boxId` -- идентификатор ящика организации.
* `messageId` -- идентификатор сообщения у оператора обмена.
* `entityId` -- идентификатор сущности у оператора ЭДО, извещение о получении которой отправляется.
* `certificate` -- сертификат, которым подписывается извещение.
* `positionName` -- должность подписывающего извещение сотрудника.

В стандартной конфигурации модуля метод вызывается, когда пользователь вызывает функцию отправки извещения.

|`GenerateInvoiceReply(String, String, String, X509Certificate2, String, String)`
a|Формирует ответную подпись для поступившего документа.

*Тип возвращаемого значения*: `xref:api/MessageFile.adoc[MessageFile]`.

.Параметры:
* `boxId` -- идентификатор ящика организации.
* `messageId` -- идентификатор сообщения у оператора обмена.
* `entityId` -- идентификатор сущности у оператора ЭДО, по которой формируется подпись.
* `certificate` -- сертификат, которым подписывается запрос.
* `documentType` -- тип документа.
* `replyData` -- содержимое ответа.

В стандартной конфигурации модуля метод вызывается, когда пользователь подписывает поступивший документ.

|`GenerateRevocationRequest(String, String, String, X509Certificate2, String, String)`
a|Формирует запрос на аннулирование.

*Тип возвращаемого значения*: `xref:api/MessageFile.adoc[MessageFile]`.

.Параметры:
* `boxId` -- идентификатор ящика организации.
* `messageId` -- идентификатор сообщения у оператора обмена.
* `entityId` -- идентификатор сущности у оператора ЭДО, по которому отправляется запрос на аннулирование.
* `certificate` -- сертификат, которым подписывается запрос.
* `positionName` -- должность подписывающего запрос сотрудника.
* `comment` -- комментарий к запросу.

В стандартной конфигурации модуля метод вызывается, когда пользователь запрашивает аннулирование.

|`GenerateSignatureRejection(String, String, String, X509Certificate2, String, String`)
a|Формирует отказ в подписании.

*Тип возвращаемого значения*: `xref:api/MessageFile.adoc[MessageFile]`.

.Параметры:
* `boxId` -- идентификатор ящика организации.
* `messageId` -- идентификатор сообщения у оператора обмена.
* `entityId` -- идентификатор сущности у оператора ЭДО, по которому отправляется отказ в подписании.
* `certificate` -- сертификат, которым подписывается ответ.
* `positionName` -- должность подписывающего запрос сотрудника.
* `comment` -- комментарий к отказу.

В стандартной конфигурации модуля метод вызывается, когда пользователь отказывает в подписании поступившего документа.

|`GetLastEventId(String)`
a|Возвращает идентификатор последнего события в ящике организации.

*Тип возвращаемого значения*: `String`.

.Параметры:
* `boxId` -- идентификатор ящика организации.

В стандартной конфигурации модуля метод используется при активации ящика организации.

|`GetNewEvents(String, String, DateTime?)`
a|Получает новые события из ящика организации.

*Тип возвращаемого значения*: `ItemCollection<xref:api/MessageData.adoc[MessageData]>`.

.Параметры:
* `boxId` -- идентификатор ящика организации.
* `lastEventId` -- идентификатор последнего полученного события (может отсутствовать).
* `fromDate` -- дата минимальная дата создания сообщения. Если значение указано, то должны возвращаться сообщения, созданные после указанной даты.

В стандартной конфигурации модуля метод вызывается при получении новых сообщений от оператора ЭДО.

|`GetNewEventsCount(String, String)`
a|Возвращает количество новых событий.

*Тип возвращаемого значения*: `Int32`.

.Параметры:
* `boxId` -- идентификатор ящика организации.
* `lastEventId` -- идентификатор последнего полученного события (может отсутствовать).

В стандартной конфигурации модуля метод вызывается при активации ящика организации.

|`Initialize(Dictionary<String, String>)`
a|Инициализирует компонент.

.Параметры:
* `settings` -- коллекция настроек оператора ЭДО из _Справочника настроек операторов ЮЗДО_. Каждая запись содержит ключ и значение, например: `Login` и {dv}@diadoc.ru.

|`SendCorrection(MessageData)`
a|Отправляет запрос на уточнение.

.Параметры:
* `messageData` -- сообщение типа `xref:api/MessageData.adoc[MessageData]`, содержащее запрос на уточнение.

В стандартной конфигурации модуля метод используется отправке новых сообщений оператору ЭДО.

|`SendMessage(MessageData)`
a|Отправляет новое сообщение оператору ЭДО.

.Параметры:
* `messageData` -- сообщение типа `xref:api/MessageData.adoc[MessageData]`.

В стандартной конфигурации модуля метод используется отправке новых сообщений оператору ЭДО.

|`SendReceipt(MessageData)`
a|Отправляет квитанцию.

.Параметры:
* `messageData` -- сообщение типа `xref:api/MessageData.adoc[MessageData]`.

|`SendRevocation(MessageData)`
a|Отправляет запрос на аннулирование.

.Параметры:
* `messageData` -- сообщение типа `xref:api/MessageData.adoc[MessageData]`, содержащее запрос на аннулирование

В стандартной конфигурации модуля метод используется отправке новых сообщений оператору ЭДО.

|`SendSignatureReply(MessageData)`
a|Отправляет ответную подпись на полученное сообщение.

.Параметры:
* `messageData` -- сообщение типа `xref:api/MessageData.adoc[MessageData]`.

В стандартной конфигурации модуля метод используется при отправке оператору ЭДО ответа на полученное сообщение.
|===
