= ISignatureService -- интерфейс

Интерфейс `ISignatureService` определяет методы, которые должен реализовывать компонент xref:signature-service.adoc[сервиса подписей].

* *Пространство имен:* `DocsVision.Edi.Interfaces`
* *Сборка:* `DocsVision.Edi.Interfaces.dll`

== Синтаксис

[source,csharp]
----
public interface ISignatureService
----

== Свойства

[cols=",",options="header",]
|===
|Имя |Описание

|`CreateCommentSignature(String, X509Certificate2)`
a|Создаёт в {dv} подпись для текстового сообщения. Метод должен вернуть идентификатор созданной подписи.

*Тип возвращаемого значения*: `Guid`.

.Параметры:
* `commentText` -- подписываемое текстовое сообщение.
* `certificate` -- сертификат подписи.

В стандартной конфигурации модуля метод вызывается, например, при подписании комментария к отказу в подписании полученного документа.

|`CreateFileSignature(MessageFile, X509Certificate2)`
a|Создаёт в {dv} подпись для файла сообщения. Метод должен вернуть идентификатор созданной подписи.

*Тип возвращаемого значения*: `Guid`.

.Параметры:
* `messageFile` -- подписываемый файл.
* `certificate` -- сертификат подписи.

В стандартной конфигурации модуля метод вызывается, например, при подписании файла сообщения с запросом уточнения для полученного документа.

|`Initialize(ObjectContext)`
a|Инициализирует экземпляр компонента сервиса подписей.

.Параметры:
* `objectContext` -- контекст объектов.
|===
