= MessageFile -- класс

Содержит данные файла электронного обмена с оператором ЭДО.

* *Пространство имен:* `DocsVision.Edi.Entities`
* *Сборка:* `DocsVision.Edi.Interfaces.dll`

== Синтаксис

[source,csharp]
----
public class MessageFile
----

== Конструкторы

[cols=",",options="header"]
|===
|Имя |Описание

|`MessageFile(Guid, String)`
a|Инициализирует новый экземпляр класса `MessageFile`.

.Параметры:
* `fileId` -- идентификатор файла.
* `fileName` -- название файла.

|`MessageFile(String, String, String)`
a|Инициализирует новый экземпляр класса `MessageFile` с указанием идентификатора файла у оператора ЭДО, названием файла и идентификатором подписи у оператора ЭДО.

.Параметры:
* `operatorFileId` -- идентификатор файла у оператора ЭДО.
* `fileName` -- название файла.
* `operatorSignatureId` -- идентификатор подписи файла у оператора ЭДО.

|`MessageFile(MessageFileType, String, String, String)`
a|Инициализирует новый экземпляр класса `MessageFile` с указанием типа сообщения, идентификатора файла у оператора ЭДО, названием файла и идентификатором подписи у оператора ЭДО.

.Параметры:
* `fileType` -- тип содержимого.
* `operatorFileId` -- идентификатор файла у оператора ЭДО.
* `fileName` -- название файла.
* `operatorParentEntityId` -- идентификатор сущности, к которой относится файл у оператора ЭДО.
|===

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание

|`FileComment`
a|Задает или возвращает комментарий к файлу.

*Тип*: `System.String`

|`FileData`
a|Задает или возвращает бинарные данные файла.

*Тип*: `Byte`

|`FileId`
a|Задает или возвращает идентификатор файла в {dv}.

*Тип*: `System.Guid`

|`FileName`
a|Задает или возвращает название файла.

*Тип*: `System.String`

|`FilePath`
a|Задает или возвращает путь, по которому выгружен файл.

*Тип*: `System.String`

|`FileType`
a|Задает или возвращает тип содержимого.

*Тип*: `xref:api/MessageFileType.adoc[MessageFileType]`

|`OperatorFileId`
a|Задает или возвращает идентификатор файла у оператора ЭДО.

*Тип*: `System.String`

|`OperatorParentEntityId`
a|Задает или возвращает идентификатор сущности, к которой относится файл у оператора ЭДО.

*Тип*: `System.String`

|`OperatorSignatureId`
a|Задает или возвращает идентификатор подписи у оператора ЭДО.

*Тип*: `System.String`

|`SignatureData`
a|Задает или возвращает бинарные данные подписи файла.

*Тип*: `Byte`

|`SignatureFilePath`
a|Задает или возвращает путь, по которому выгружена подпись файла.

*Тип*: `System.String`
|===
