= Карточки {dv} для работы с формализованными документами

Для работы с формализованными документами в  модуле предусмотрено несколько специальных видов карточек, производных от вида _Документ_:

. _Исходящий УПД_ -- предназначен для создания исходящих УПД.
.. _Исходящий УКД_ -- предназначен для создания корректировок к отправленным УПД.
.. _Исходящее исправление УПД_ -- предназначен для формирования исправлений отправленных УПД.
... _Исходящее исправление УПД (820)_ -- предназначен для формирования исправлений для отправленных УПД в формате, вступающем в силу в 2020 году.
.. _Исходящий УПД (820)_ -- предназначен для создания исходящих УПД в формате, вступающем в силу в 2020 году.
. _Входящий УПД_ -- предназначен для работы с входящими УПД. Карточки данного вида создаются  модулем при получении формализованных документов.
.. _Входящий УКД_ -- предназначен для работы с корректировками полученных УПД.
.. _Входящий УПД (820)_ -- предназначен для работы с корректировками полученных УПД в формате, вступающем в силу в 2020 году.
.. _Формализованный акт_ -- предназначен для работы с входящими актами и формализованными накладными в рекомендованном ФНС формате.
... _Формализованный акт (820)_ -- предназначен для работы с входящими актами и формализованными накладными в рекомендованном ФНС формате, вступающем в силу в 2020 году.
