= Работа с исходящими документами

.Работа с исходящими документами включает следующие этапы:
. Пользователь модуля (далее -- _Продавец_) создаёт исходящий документ вида (или подвида) _Исходящий УПД_ и отправляет его контрагенту (далее -- _Покупатель_).
. Оператор ЭДО принимает документ от _Продавца_ и отправляет ему Извещение о получении, а также передаёт документ Покупателю.
. Продавец получает Извещение о получении от оператора ЭДО и подтверждает его получение. Подтверждение не требуется для актов и накладных.
. После получения документа Покупатель может:
+
* Подписать или отказать в подписании документа -- не требуется для счёт-фактуры.
+
include::partial$tin.adoc[]
+
* Запросить аннулирование -- для счёт-фактуры.
* Запросить уточнение у _Продавца_.
+
. _Продавец_ получает ответ от _Покупателя_.
+
.Если "Покупатель" подписал документ (был сформирован титул покупателя):
.. Титул покупателя добавляется в карточку _Исходящего УПД_ (или подвида).
.. Карточка и статус обмена переходят в состояние `Получена подпись от контрагента`.
.. Документооборот завершен.
+
* Если _Покупатель_ отказал в подписании документа, карточка и статус обмена переходят в состояние "Получен отказ от контрагента".
* Если _Покупатель_ запросил уточнение, статус обмена переходит в состояние `Требуется подтверждение получения`, а далее в `Требуется уточнение`. После этого работа с данным документом завершается. Пользователь модуля может создать корректировочный УПД или исправление УПД.
+
. _Покупатель_ или _Продавец_ могут запросить аннулирование подписанного документа. Вторая сторона ЭДО может подтвердить или отказать в аннулировании.
+
Если _Продавец_ запросил аннулирование до получения извещения от оператора ЭДО (о получении документа от _Продавца_), документ будет аннулирован в одностороннем порядке (без подтверждения со стороны _Покупателя_).
