= Department - класс

Содержит данные подразделения организации или контрагента, полученные от оператора ЭДО.

* [.keyword]*Пространство имен:* {dv}.Edi.Entities
* [.keyword]*Сборка:* `{dv}.Edi.Interfaces.dll`

=== Синтаксис

[source,pre,codeblock,language-csharp]
----
public class Department
----

=== Конструкторы

[cols=",",options="header",]
|===
|Имя |Описание
|Department(String, String, String) a|
Инициализирует новый экземпляр класса Department.

Параметры:

* id - идентификатор подразделения у оператора ЭДО
* name - название подразделения у оператора ЭДО
* kpp - КПП подразделения у оператора ЭДО

|===

=== Свойства

[cols=",",options="header",]
|===
|Имя |Описание
|Departments a|
Возвращает коллекцию подчиненных подразделений.

Тип: ItemCollection<xref:Department.adoc[Department]>

|Id a|
Задает или возвращает идентификатор подразделения в системе оператора ЭДО.

Тип: [.keyword .apiname]#System.String#

|Kpp a|
Задает или возвращает КПП подразделения в системе оператора ЭДО.

Тип: [.keyword .apiname]#System.String#

|Name a|
Задает или возвращает название подразделения в системе оператора ЭДО.

Тип: [.keyword .apiname]#System.String#

|===
