= EdiMessageMainInfo - класс

Содержит основную информацию _Карточки обмена сообщениями_.

* [.keyword]*Пространство имен:* {dv}.Edi.ObjectModel
* [.keyword]*Сборка:* `{dv}.Edi.ObjectModel.dll`

=== Синтаксис

[source,pre,codeblock,language-csharp]
----
public class EdiMessageMainInfo : BaseCardSectionRow
----

=== Свойства

[cols=",",options="header",]
|===
|Имя |Описание
|CardId a|
Задает или возвращает идентификатор карточки, с которой связано сообщение.

Тип: [.keyword .apiname]#System.Guid#

|MessageState a|
Задает или возвращает состояние сообщения.

Тип: [.keyword .apiname]#EdiMessageState#

|OperatorMessageId a|
Задает или возвращает идентификатор сообщения у оператора.

Тип: [.keyword .apiname]#System.String#

|OrganizationBox a|
Задает или возвращает ящик организации.

Тип: [.keyword .apiname]#OperatorsBox#

|OrganizationDepartment a|
Задает или возвращает подразделение организации.

Тип: [.keyword .apiname]#OperatorsDepartment#

|Partner a|
Задает или возвращает контрагента.

Тип: [.keyword .apiname]#PartnersCompany#

|PartnerBox a|
Задает или возвращает ящик контрагента.

Тип: [.keyword .apiname]#OperatorsPartnerBox#

|PartnerDepartment a|
Задает или возвращает подразделение контрагента.

Тип: [.keyword .apiname]#OperatorsPartnerDepartment#

|===

=== Поля

[cols=",",options="header",]
|===
|Имя |Описание
|CardIdProperty |Определяет свойство "Карточка".
|MessageStateProperty |Определяет свойство "Состояние".
|OperatorMessageIdProperty |Определяет свойство "Идентификатор сообщения у оператора".
|OrganizationBoxProperty |Определяет свойство "Ящик организации".
|OrganizationDepartmentProperty |Определяет свойство "Подразделение организации".
|PartnerBoxProperty |Определяет свойство "Ящик контрагента".
|PartnerDepartmentProperty |Определяет свойство "Подразделение контрагента".
|PartnerProperty |Определяет свойство "Контрагент".
|===
