= EdiMessageLogItem - класс

Содержит данные записи в журнале из _Карточки обмена сообщениями_.

* [.keyword]*Пространство имен:* {dv}.Edi.ObjectModel
* [.keyword]*Сборка:* `{dv}.Edi.ObjectModel.dll`

=== Синтаксис

[source,pre,codeblock,language-csharp]
----
public class EdiMessageLogItem : BaseCardSectionRow
----

=== Свойства

[cols=",",options="header",]
|===
|Имя |Описание
|Comment a|
Задает или возвращает текст комментария.

Тип: [.keyword .apiname]#System.String#

|Date a|
Задает или возвращает дату записи.

Тип: [.keyword .apiname]#System.DateTime#

|Description a|
Задает или возвращает текст сообщения.

Тип: [.keyword .apiname]#System.String#

|EventType a|
Задает или возвращает тип события.

Тип: xref:EdiMessageEventType.adoc[EdiMessageEventType]

|FileName a|
Задает или возвращает название файла, с которым связано событие.

Тип: [.keyword .apiname]#System.String#

|SignedFile a|
Задает или возвращает подписанный файл.

Тип: xref:EdiMessageSignedFile.adoc[EdiMessageSignedFile]

|===

=== Поля

[cols=",",options="header",]
|===
|Имя |Описание
|CommentProperty |Определяет свойство "Комментарий".
|DateProperty |Определяет свойство "Дата".
|DescriptionProperty |Определяет свойство "Описание".
|EventTypeProperty |Определяет свойство "Тип события".
|FileNameProperty |Определяет свойство "Имя файла".
|SignedFileProperty |Определяет свойство "Подписанный файл".
|===
