= EdiMessage - класс

Содержит данные _Карточки обмена сообщениями_.

* [.keyword]*Пространство имен:* DocsVision.Edi.ObjectModel
* [.keyword]*Сборка:* `DocsVision.Edi.ObjectModel.dll`

=== Синтаксис

[source,csharp]
----
public class EdiMessage : BaseCard
----

=== Свойства

[cols=",",options="header",]
|===
|Имя |Описание
|Files a|
Возвращает файлы сообщения.

Тип: ObjectCollection<xref:EdiMessageFile.adoc[EdiMessageFile]>

|Log a|
Возвращает записи их журнал обмена.

Тип: ObjectCollection<xref:EdiMessageLogItem.adoc[EdiMessageLogItem]>

|MainInfo a|
Возвращает основную информацию.

Тип: xref:EdiMessageMainInfo.adoc[EdiMessageMainInfo]

|Processes |_Не используется._
|SignedComments a|
Подписанные комментарии.

Тип: ObjectCollection<xref:EdiMessageSignedComment.adoc[EdiMessageSignedComment]>

|SignedFiles a|
Подписанные файлы.

Тип: ObjectCollection<xref:EdiMessageSignedFile.adoc[EdiMessageSignedFile]>

|SystemInfo |_Не используется._
|TransferData a|
Данные для переноса.

ObjectCollection<xref:EdiMessageTransferData.adoc[EdiMessageTransferData]>

|===

=== Поля

[cols=",",options="header",]
|===
|Имя |Описание
|FilesProperty |Определяет свойство "Файлы".
|LogProperty |Определяет свойство "Журнал обмена".
|MainInfoProperty |Определяет свойство "Основная информация".
|SignedCommentsProperty |Определяет свойство "Подписанные комментарии".
|SignedFilesProperty |Определяет свойство "Подписанные файлы".
|TransferDataProperty |Определяет свойство "Файлы для переноса".
|===
