= EdiMessageReplyFile - класс

Содержит данные ответного файла, полученного от контрагента, в карточке обмена сообщениями.

* [.keyword]*Пространство имен:* DocsVision.Edi.ObjectModel
* [.keyword]*Сборка:* `DocsVision.Edi.ObjectModel.dll`

=== Синтаксис

[source,csharp]
----
public class EdiMessageReplyFile : BaseCardSectionRow
----

=== Свойства

[cols=",",options="header",]
|===
|Имя |Описание
|NeedReceipt a|
Задает или возвращает флаг, указывающий на необходимость подтверждения получения.

Тип: System.Boolean

|ParentMessageFile a|
Возвращает ссылку на родительское сообщение электронного обмена.

Тип: xref:EdiMessageFile.adoc[EdiMessageFile]

|ReplyFile a|
Задает или возвращает ответный файл.

Тип: xref:EdiMessageSignedFile.adoc[EdiMessageSignedFile]

|ReplyFileType a|
Задает или возвращает тип ответного файла.

Тип: xref:EdiMessageReplyFileType.adoc[EdiMessageReplyFileType]

|ReplyReceipt a|
Задает или возвращает ссылку на ответный файл (квитанцию).

Тип: xref:EdiMessageSignedFile.adoc[EdiMessageSignedFile]

|===

=== Поля

[cols=",",options="header",]
|===
|Имя |Описание
|NeedReceiptProperty |Определяет свойство "Требуется извещение".
|ReplyFileProperty |Определяет свойство "Ответный файл".
|ReplyFileTypeProperty |Определяет свойство "Тип ответного файла".
|ReplyReceiptProperty |Определяет свойство "Ответная квитанция".
|===
