= IDocumentUpdater - интерфейс

Интерфейс [.keyword .apiname]#IDocumentUpdater# определяет методы, которые должен реализовывать xref:createcomponent_sender_updater.adoc[компонент изменения данных карточки].

* [.keyword]*Пространство имен:* {dv}.Edi.Interfaces
* [.keyword]*Сборка:* `{dv}.Edi.Interfaces.dll`

=== Синтаксис

[source,pre,codeblock,language-csharp]
----
public interface IDocumentUpdater
----

=== Методы

[cols=",",options="header",]
|===
|Имя |Описание
|AddSignatureToDocument(Guid, Guid, MessageFile, String) a|
Добавляет подпись файла в карточку.

Тип возвращаемого значения: System.Guid

Параметры:

* cardId - идентификатор карточки
* fileId - идентификатор подписываемого файла
* messageFile - поступившее сообщение электронного обмена, содержащее подпись файла
* partnerName - название контрагента

В стандартной конфигурации модуля метод вызывается, когда от оператора ЭДО поступило сообщение с ответной подписью.

|ChangeDocumentState(Guid, Guid) a|
Изменяет состояние карточки. Если изменение было успешным, метод возвращает true, иначе - false.

Тип возвращаемого значения: System.Boolean

Параметры:

* cardId - идентификатор карточки
* newStateId - идентификатор нового состояния

В стандартной конфигурации модуля метод вызывается при обработке входящих сообщений бизнес-процессом "Перенос файлов из сообщений ЮЗДО".

|CheckCertificate(Guid, X509Certificate2) a|
Проверяет соответствие подписи в указанной карточке переданному сертификату и возвращает результат проверки.

Тип возвращаемого значения: System.String

Параметры:

* cardId - идентификатор проверяемой карточки
* certificate - сертификат, для которого выполняется проверка

В стандартной конфигурации модуля метод вызывается при отправке УПД пользователем.

|CreateNewSignatures(Guid, X509Certificate2, Boolean) a|
Подписывает карточку переданным сертификатом.

Тип возвращаемого значения: System.Guid

Параметры:

* cardId - идентификатор подписываемой карточки
* certificate - сертификат, которым подписывается карточка
* signAdditionalFiles - подписывать дополнительные файлы: true - подписывать; false - не подписывать

В стандартной конфигурации модуля метод вызывается, когда пользователь подписывает карточку отправляемого электронного документа.

|GetNewStateId(MessageFileType) a|
Возвращает идентификатор встроенного состояния для карточки УПД, сопоставленного типу ответа контрагента на отправленный ранее УПД.

Тип возвращаемого значения: System.Guid

Параметры:

* messageFileType - тип ответа контрагента

В стандартной конфигурации модуля метод вызывается, когда пользователь подписывает карточку отправляемого электронного документа.

|Initialize(ObjectContext) a|
Инициализирует экземпляр компонента создания документов.

Параметры:

* objectContext - контекст объектов.

|UpdateDocumentDataFromFile(Guid, Guid) a|
Обновляет содержимое карточки данными из файла.

Параметры:

* cardId - идентификатор обновляемой карточки
* fileId - идентификатор файла, содержащего данные для обновления карточки

В стандартной конфигурации модуля метод вызывается, когда пользователь использует команду *Заполнить данные из файла* в карточке УПД.

|===
