= IImportService - интерфейс

Интерфейс IMessageService# определяет методы, которые должен реализовывать компонент xref:createcomponent_importconfig.adoc[импорта настроек ЭДО].

* [.keyword]*Пространство имен:* DocsVision.Edi.Interfaces
* [.keyword]*Сборка:* `DocsVision.Edi.Interfaces.dll`

=== Синтаксис

[source,csharp]
----
public interface IImportService
----

=== Методы

[cols=",",options="header",]
|===
|Имя |Описание
|ImportPartners a|
Предоставляет список контрагентов и их ящиков, зарегистрированных у организации в системе оператора ЭДО.

Тип возвращаемого значения: ItemCollection<xref:Partner.adoc[Partner]>

В стандартной конфигурации модуля метод используется при вызове в _Справочнике настроек операторов ЮЗДО_ команды загрузки данных контрагентов.

|ImportUnits a|
Предоставляет список подразделений организации и их ящиков ящиками, зарегистрированных у организации в системе оператора ЭДО.

Тип возвращаемого значения: ItemCollection<xref:Unit.adoc[Unit]>

В стандартной конфигурации модуля метод используется при вызове в _Справочнике настроек операторов ЮЗДО_ команды загрузки данных организации.

|Initialize(Dictionary<string, string>) a|
Инициализирует компонент.

Параметры:

* settings - коллекция настроек оператора ЭДО из _Справочника настроек операторов ЮЗДО_. Каждая запись содержит ключ и значение, например: "Login" и "{dv}@diadoc.ru".

|===

=== Примеры

См. пример реализации интерфейса в разделе xref:createcomponent_importconfig.adoc[Разработка компонента импорта настроек организации из системы оператора ЭДО].
