= Разработка компонента сервиса сообщений

Компонент сервиса сообщений предоставляет модулю не зависящий от оператора ЭДО слой отправки и получения электронных сообщений.

Компонент данного типа непосредственно взаимодействует с оператором ЭДО. При взаимодействии выполняется передача и получение сообщений электронного обмена, в т.ч. содержащих электронные документы (входящие и исходящие).

Данный компонент должен реализовывать программный интерфейс xref:api/IMessageService.adoc[IMessageService]. Методы реализуемого интерфейса вызываются при получении и отправке сообщений оператору ЭДО.

Вариант реализации данного компонента содержится в сборке `DocsVision.Edi.Runtime.Diadoc.dll` (добавляется при установке "Коннектор к Диадок").

Фактическая реализация компонента сервиса сообщений сильно зависит от метода взаимодействия с оператором ЭДО и предоставляемого им API.

Далее приведена часть исходного кода (только публичные методы) примера реализации интерфейса `IMessageService` для работы с оператором _Диадок_.

[source,csharp]
----
public class MessagesService: IMessageService <.>
{
    private DiadocSession DiadocSession <.>
    {
        get
        {
            if (diadocSession != null && !diadocSession.IsAlive())
            {
                diadocSession = null;
            }

            if (diadocSession == null)
            {
                if (!settings.ContainsKey(DiadocSettings.ApiUrl))
                {
                    throw Error.InvalidOperation(Resources.NoConnectionData);
                }

                if (!settings.ContainsKey(DiadocSettings.Login))
                {
                    throw Error.InvalidOperation(Resources.NoConnectionData);
                }

                diadocSession = new DiadocSession(
                    settings[DiadocSettings.ApiUrl],
                    settings[DiadocSettings.Login],
                    settings[DiadocSettings.Password],
                    settings.ContainsKey(DiadocSettings.ProxyUrl) ? settings[DiadocSettings.ProxyUrl] : null,
                    settings.ContainsKey(DiadocSettings.ProxyLogin) ? settings[DiadocSettings.ProxyLogin] : null,
                    settings.ContainsKey(DiadocSettings.ProxyPassword) ? settings[DiadocSettings.ProxyPassword] : null);
            }

            return diadocSession;
        }
    }
<.>
    public void Initialize(Dictionary<string, string> settings) <.>
    {
        this.settings = settings;
    }
        
    public void SendMessage(MessageData messageData) <.>
    {
        DiadocSession.SendMessage(messageData);
    }

    public void SendSignatureReply(MessageData messageData) <.>
    {
        DiadocSession.SendSignatureReply(messageData);
    }

    public void SendReceipt(MessageData messageData) <.>
    {
        DiadocSession.SendReceipt(messageData);
    }

    public void SendRevocation(MessageData messageData) <.>
    {
        DiadocSession.SendRevocation(messageData);
    }

    public void SendCorrection(MessageData messageData) <.>
    {
        DiadocSession.SendCorrection(messageData);
    }

    public int GetNewEventsCount(string boxId, string lastEventId) <.>
    {
        return DiadocSession.GetNewEventsCount(boxId, lastEventId);
    }

    public string GetLastEventId(string boxId) <.>
    {
        return DiadocSession.GetLastEventId(boxId, null);
    }

    public bool EventExists(string boxId, string eventId) <.>
    {
        return DiadocSession.EventExists(boxId, eventId);
    }

    public ItemCollection<MessageData> GetNewEvents(string boxId, string lastEventId, DateTime? fromDate) <.>
    {
        return DiadocSession.GetNewEvents(boxId, lastEventId, fromDate);
    }

    public MessageFile GenerateInvoiceReceipt(string boxId, string messageId, string entityId, X509Certificate2 certificate, string positionName) <.>
    {
        return DiadocSession.GenerateInvoiceReceipt(boxId, messageId, entityId, certificate, positionName);
    }

    public MessageFile GenerateRevocationRequest(string boxId, string messageId, string entityId, <.>
        X509Certificate2 certificate, string positionName, string comment)
    {
        return DiadocSession.GenerateRevocationRequest(boxId, messageId, entityId, certificate, positionName, comment);
    }

    public MessageFile GenerateInvoiceReply(string boxId, string messageId, string entityId, X509Certificate2 certificate, string documentType, string replyData) <.>
    {
        return DiadocSession.GenerateInvoiceReply(boxId, messageId, entityId, certificate, documentType, replyData);
    }

    public MessageFile GenerateSignatureRejection(string boxId, string messageId, string entityId, <.>
        X509Certificate2 certificate, string positionName, string comment)
    {
        return DiadocSession.GenerateSignatureRejection(boxId, messageId, entityId, certificate, positionName, comment);
    }

    public MessageFile GenerateCorrectionRequest(string boxId, string messageId, string entityId, <.>
        X509Certificate2 certificate, string positionName, string comment)
    {
        return DiadocSession.GenerateCorrectionRequest(boxId, messageId, entityId, certificate, positionName, comment);
    }
}
----
<.> Компонент сервиса сообщение.
<.> Точка доступа к API Диадок.
<.> Реализация интерфейса IMessageService.
<.> Инициализация компонента.
<.> Реализация метода отправки сообщения оператору ЭДО.
<.> Реализация метода отправки ответной подписи.
<.> Реализация метода отправки квитанции.
<.> Реализация метода отправки запроса на аннулирование.
<.> Реализация метода отправки запроса на уточнение.
<.> Реализация метода получения количества новых событий.
<.> Реализация метода получения идентификатора последнего события в ящике организации.
<.> Реализация метода проверки наличия события в ящике.
<.> Реализация метода получения новых событий из ящика.
<.> Реализация метода формирования извещения.
<.> Реализация метода формирования запроса на аннулирование.
<.> Реализация метода формирования ответной подписи для поступившего документа.
<.> Реализация метода формирования сообщения с отказом в подписании.
<.> Реализация метода формирования запроса на уточнение.

Далее приведена часть исходного кода класса `DiadocSession`, в котором показан принцип взаимодействия с оператором ЭДО через его API на примере получения идентификатора последнего сообщения.

[source,csharp]
----
public class DiadocSession 
{
    private readonly DiadocApi DiadocApi; <.>
    private readonly string AuthToken;

       public DiadocSession(string apiUrl, string login, string password, string proxyUrl, string proxyLogin, string proxyPassword)
    {
        WinApiCrypt diadocCrypt = new WinApiCrypt();
        DiadocApi = new DiadocApi(DefaultClientId, apiUrl, diadocCrypt);

        if (!string.IsNullOrEmpty(proxyUrl))
        {
            DiadocApi.DisableSystemProxyUsage();
            DiadocApi.SetProxyUri(proxyUrl);
            if (!string.IsNullOrEmpty(proxyLogin))
                DiadocApi.SetProxyCredentials(proxyLogin, proxyPassword);
        }

        AuthToken = DiadocApi.Authenticate(login, password);
    }

       public string GetLastEventId(string boxId, string lastEventId) <.>
    {
        while (true)
        {
            BoxEventList eventList = DiadocApi.GetNewEvents(AuthToken, boxId, lastEventId);
            if (eventList == null || eventList.TotalCount == 0)
                return lastEventId;

            lastEventId = eventList.Events[eventList.Events.Count -- 1].EventId;
            if (eventList.TotalCount == eventList.Events.Count)
                return lastEventId;
        }
    }

}
----
<.> DiadocApi -- объект API Диадок, проксирующий работу с веб-сервисом Диадок. +
Описание API Диадок приведено на странице с документацией Диадок API.
<.> Получаем идентификатор последнего события в ящике организации.

