= MessageFile - класс

Содержит данные файла электронного обмена с оператором ЭДО.

* [.keyword]*Пространство имен:* {dv}.Edi.Entities
* [.keyword]*Сборка:* `{dv}.Edi.Interfaces.dll`

=== Синтаксис

[source,pre,codeblock,language-csharp]
----
public class MessageFile
----

=== Конструкторы

[cols=",",options="header",]
|===
|Имя |Описание
|MessageFile(Guid, String) a|
Инициализирует новый экземпляр класса MessageFile.

Параметры:

* fileId - идентификатор файла
* fileName - название файла

|MessageFile(String, String, String) a|
Инициализирует новый экземпляр класса MessageFile с указанием идентификатора файла у оператора ЭДО, названием файла и идентификатором подписи у оператора ЭДО.

Параметры:

* operatorFileId - идентификатор файла у оператора ЭДО
* fileName - название файла
* operatorSignatureId - идентификатор подписи файла у оператора ЭДО

|MessageFile(MessageFileType, String, String, String) a|
Инициализирует новый экземпляр класса MessageFile с указанием типа сообщения, идентификатора файла у оператора ЭДО, названием файла и идентификатором подписи у оператора ЭДО.

Параметры:

* fileType - тип содержимого
* operatorFileId - идентификатор файла у оператора ЭДО
* fileName - название файла
* operatorParentEntityId - идентификатор сущности, к которой относится файл у оператора ЭДО

|===

=== Свойства

[cols=",",options="header",]
|===
|Имя |Описание
|FileComment a|
Задает или возвращает комментарий к файлу.

Тип: [.keyword .apiname]#System.String#

|FileData a|
Задает или возвращает бинарные данные файла.

Тип: Byte

|FileId a|
Задает или возвращает идентификатор файла в {dv}.

Тип: [.keyword .apiname]#System.Guid#

|FileName a|
Задает или возвращает название файла.

Тип: [.keyword .apiname]#System.String#

|FilePath a|
Задает или возвращает путь, по которому выгружен файл.

Тип: [.keyword .apiname]#System.String#

|FileType a|
Задает или возвращает тип содержимого.

Тип: xref:MessageFileType.adoc[MessageFileType]

|OperatorFileId a|
Задает или возвращает идентификатор файла у оператора ЭДО.

Тип: [.keyword .apiname]#System.String#

|OperatorParentEntityId a|
Задает или возвращает идентификатор сущности, к которой относится файл у оператора ЭДО.

Тип: [.keyword .apiname]#System.String#

|OperatorSignatureId a|
Задает или возвращает идентификатор подписи у оператора ЭДО.

Тип: [.keyword .apiname]#System.String#

|SignatureData a|
Задает или возвращает бинарные данные подписи файла.

Тип: Byte

|SignatureFilePath a|
Задает или возвращает путь, по которому выгружена подпись файла.

Тип: [.keyword .apiname]#System.String#

|===
