= MessageAddress - класс

Содержит данные отправителя или получателя сообщения электронного обмена.

* [.keyword]*Пространство имен:* {dv}.Edi.Entities
* [.keyword]*Сборка:* `{dv}.Edi.Interfaces.dll`

=== Синтаксис

[source,pre,codeblock,language-csharp]
----
public class MessageAddress
----

=== Конструкторы

[cols=",",options="header",]
|===
|Имя |Описание
|MessageAddress(String) a|
Инициализирует новый экземпляр класса MessageAddress.

Параметры:

* boxId - идентификатор ящика электронного обмена

|MessageAddress(String, String) a|
Инициализирует новый экземпляр класса MessageAddress.

Параметры:

* boxId - идентификатор ящика электронного обмена
* name - название ящика электронного обмена

|===

=== Свойства

[cols=",",options="header",]
|===
|Имя |Описание
|BoxId a|
Задает или возвращает идентификатор ящика электронного обмена.

Тип: [.keyword .apiname]#System.String#

|DepartmentId a|
Задает или возвращает идентификатор подразделения отправителя или получателя.

Тип: [.keyword .apiname]#System.String#

|Name a|
Задает или возвращает название отправителя или получателя.

Тип: [.keyword .apiname]#System.String#

|===
