= Partner - класс

Содержит данные контрагента, полученные от оператора ЭДО.

* [.keyword]*Пространство имен:* {dv}.Edi.Entities
* [.keyword]*Сборка:* `{dv}.Edi.Interfaces.dll`

=== Синтаксис

[source,pre,codeblock,language-csharp]
----
public class Partner
----

=== Конструкторы

[cols=",",options="header",]
|===
|Имя |Описание
|Partner(String, String, String) a|
Инициализирует новый экземпляр класса Partner.

Параметры:

* id - идентификатор контрагента у оператора ЭДО
* name - название контрагента у оператора ЭДО
* inn - ИНН контрагента у оператора ЭДО

|===

=== Свойства

[cols=",",options="header",]
|===
|Имя |Описание
|Departments a|
Возвращает коллекцию подразделений контрагента.

Тип: ItemCollection<xref:Department.adoc[Department]>

|Id a|
Задает или возвращает идентификатор контрагента в системе оператора ЭДО.

Тип: [.keyword .apiname]#System.String#

|Inn a|
Задает или возвращает ИНН контрагента в системе оператора ЭДО.

Тип: [.keyword .apiname]#System.String#

|LinkedBoxes a|
Возвращает коллекцию связанных ящиков контрагента.

Тип: ItemCollection<xref:Box.adoc[Box]>

|Name a|
Задает или возвращает название контрагента в системе оператора ЭДО.

Тип: [.keyword .apiname]#System.String#

|PartnerBoxes a|
Возвращает коллекцию ящиков контрагента.

Тип: ItemCollection<xref:Box.adoc[Box]>

|===
