= Общие сведения о коннекторе

== Назначение и функции Коннектора

_{txc}_ является дополнительным компонентом _{of-em}_, который добавляет поддержку работы с системой {tx}.

Коннектор предоставляет следующие возможности:

* Отправка и получение электронных документов через систему {tx}.
* Получение списка организаций и контрагентов, зарегистрированных в системе {tx}.

== Необходимые ресурсы

[cols=",",options="header"]
|===
|Требование
|Описание требования

|Необходимое техническое обеспечение
|Специальные требования к аппаратному обеспечению не предъявляются.

|Необходимое программное обеспечение
|Серверная и клиентская части _{of-em}_ версии {edi-req-tx} и выше.

|Требования к каналам связи
a|Администратор локальной сети должен обеспечить возможность подключения с сервера {dv} и серверов СУБП к сервису {tx}.

* Стандартная точка подключения к сервису "{tx}": \https://invoice.taxcom.ru/.
* Адрес тестового сервиса "{tx}": \https://integration.taxcom.ru/

|Лицензия
|Для работы с Коннектором лицензия на систему {dv} должна содержать дополнительную опцию _{dv} {txc}_.

|Учётная запись в системе {tx}
a|Для передачи электронных документов через систему {tx} необходимо быть зарегистрированным пользователем данной системы. Регистрация организации в системе {tx} выполняется самостоятельно.

Для загрузки контрагентов требуется подключение к системе {tx} с тарифом, включающим оплату доступа к API. В противном случае при загрузке контрагентов в журнале сервера будет появляться ошибка "Необходима оплата тарифа АПИ". Если учетная запись используется в нескольких независимых организациях с разными тарифами, конкретно для коннектора можно сделать отдельную учетную запись и добавить её только в организации с доступом к API.

[NOTE]
====
Информация о подключении к системе {tx} приведена на сайте https://taxcom.ru/.
====
|===
