= Общие сведения о коннекторе

== Назначение и функции Коннектора

_Коннектор к СБИС_ является дополнительным компонентом _{of-em}_, который добавляет поддержку работы с оператором СБИС.

.Коннектор предоставляет следующие возможности:
* Добавление своей организации в справочник настроек операторов ЮЗДО.
* Загрузка контрагентов из кабинета СБИС.
* Загрузка документов, по которым завершён документооборот, при активации ящика ЮЗДО.
* Отправка формализованных и неформализованных документов, в т.ч. с МЧДfootnote:[Коннектор к СБИС данной версии поддерживает только работу с МЧД без xref:system:ROOT:terms.adoc#attorney[СКД].], отображаемой в Журнале обмена.
* Получение и подписание входящих формализованных и неформализованных документов, в т.ч. с МЧД, отображаемой в Журнале обмена.

[WARNING]
====
include::webuser:partial$sbis.adoc[]

При использовании коннектора к СБИС в разметках УПД и УКД будет скрыта кнопка *Запросить уточнение*.
====

== Необходимые ресурсы

[cols=",",options="header"]
|===
|Требование
|Описание требования

|Необходимое техническое обеспечение
|Специальные требования к аппаратному обеспечению не предъявляются.

|Необходимое программное обеспечение
|Серверная и клиентская части _{of-em}_ версии {edi-req} и выше.

|Требования к каналам связи
|Администратор локальной сети должен обеспечить возможность подключения с сервера {dv} и серверов СУБП к сервису оператора СБИС. Стандартная точка подключения: "https://online.sbis.ru/".

|Лицензия
|Для работы с Коннектором лицензия на систему {dv} должна содержать дополнительную опцию _{dv} Коннектор к СБИС_.

|Учётная запись в системе СБИС
a|Для передачи электронных документов через оператора ЭДО "СБИС" необходимо быть зарегистрированным пользователем данной системы. Регистрация организации в системе "СБИС" выполняется самостоятельно.

Для загрузки контрагентов требуется подключение к ЭДО "СБИС" с тарифом, включающим оплату доступа к API. В противном случае при загрузке контрагентов в журнале сервера будет появляться ошибка "Необходима оплата тарифа АПИ". Если учетная запись используется в нескольких независимых организациях с разными тарифами, конкретно для коннектора можно сделать отдельную учетную запись и добавить её только в организации с доступом к API.

[NOTE]
====
Информация о подключении к оператору СБИС приведена на сайте https://www.sbis.ru/.
====
|===
