= Общие сведения о коннекторе

== Назначение и функции Коннектора

_Коннектор к СБИС_ является дополнительным компонентом _{of-em}_, который добавляет поддержку работы с системой СБИС оператора ЭДО Тензор.

.Коннектор предоставляет следующие возможности:
* Добавление своей организации в справочник настроек операторов ЮЗДО.
* Загрузка контрагентов из кабинета СБИС.
* Загрузка документов, по которым завершён документооборот, при активации ящика ЮЗДО.
* Отправка формализованных и неформализованных документов, в т.ч. с МЧД, отображаемой в Журнале обмена.
* Получение и подписание входящих формализованных и неформализованных документов, в т.ч. с МЧД, отображаемой в Журнале обмена.

[WARNING]
====
include::webuser:partial$sbis.adoc[]

При работе с коннектором к СБИС в разметках УПД и УКД кнопку *Запросить уточнение* необходимо скрыть.
====

== Необходимые ресурсы

[cols=",",options="header"]
|===
|Требование
|Описание требования

|Необходимое техническое обеспечение
|Специальные требования к аппаратному обеспечению не предъявляются.

|Необходимое программное обеспечение
|Серверная и клиентская части _{of-em}_ версии {edi-req} и выше.

|Требования к каналам связи
|Администратор локальной сети должен обеспечить возможность подключения с сервера {dv} и серверов СУБП к системе СБИС.

|Лицензия
|Для работы с Коннектором лицензия на систему {dv} должна содержать дополнительную опцию _{dv} Коннектор к СБИС_.

|Учётная запись в системе СБИС
a|Для передачи электронных документов через систему СБИС необходимо быть зарегистрированным пользователем данной системы. Регистрация организации в системе СБИС выполняется самостоятельно.

Для загрузки контрагентов требуется подключение к системе СБИС с тарифом, включающим оплату доступа к API. В противном случае при загрузке контрагентов в журнале сервера будет появляться ошибка "Необходима оплата тарифа АПИ". Если учетная запись используется в нескольких независимых организациях с разными тарифами, конкретно для коннектора можно сделать отдельную учетную запись и добавить её только в организации с доступом к API.

[NOTE]
====
Информация о подключении к системе СБИС приведена на сайте https://www.sbis.ru/.
====
|===
