= Настройка функций обмена неформализованными документами

Для работы с неформализованными документами администратору нужно настроить разметки карточек Docsvision, которые будут использоваться для обмена электронными документами: для отправки, получения и аннулирования.

Стандартные настройки модуля предусматривают, что для получения электронных документов будет использоваться вид "Документ/Входящий", а для отправки – любой вид документа (например, "Документ/Исходящий").

[NOTE]
====
[.note__title]#Прим.:# Виды "Входящий" и "Исходящий" являются стандартными видами для организации ЭДО неформализованными документами, но не обязательными. При организации ЭДО на других видах карточек настройте xref:OutputInfo.adoc[отправку] и xref:InputInfo.adoc[получение] с их использованием в Справочнике настроек операторов ЮЗДО.
====

[[concept_ivq_bbt_zz__section_vpc_sm2_gjb]]
=== Настройка разметки вида "Документ/Входящий"

. Откройте в [.dfn .term]_Конструкторе разметок_ настройки вида [.dfn .term]_Документ/Входящий_.
. Добавьте на ленту карточки новую группу с названием "Электронный обмен".
. Добавьте в группу "Электронный обмен" команды:
* "Подписание документа",
* "Отказ в подписании документа",
* "Запросить аннулирование",
* "Подтвердить аннулирование",
* "Отказать в аннулировании".
. Укажите операции доступа для добавленных команд.
. Добавьте в скрипт карточки обработчики для новых команд.
[loweralpha]
.. Добавьте в скрипт карточки ссылку на дополнительную сборку [.ph .filepath]`DocsVision.Edi.DocumentScript.dll` (располагается в каталоге клиента Docsvision).
+
[NOTE]
====
[.note__title]#Прим.:# Рекомендуется подключать сборку по её полному имени, а не с указанием абсолютного пути. См. https://docsvision.zendesk.com/hc/ru/community/posts/115000543144-%D0%9A%D0%B0%D0%BA-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-%D1%81%D0%BE%D0%B1%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B8-%D0%BD%D0%B0-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B5-[рекомендации на Портале технической поддержки Docsvision] (требуется регистрация).
====
.. В раздел подключаемых пространств имен добавьте:
+
[source,pre,codeblock,language-csharp]
----
using DocsVision.Edi.DocumentScript;
----
.. Добавьте обработчики для новых команд:
* для команды "Подписание документа":
+
[source,pre,codeblock,language-csharp]
----
private void sendReplySignature_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
  EdiScriptHelper ediScriptHelper = new EdiScriptHelper(CardControl);           
  ediScriptHelper.SendReplySignature();
}
----
* для команды "Отказ в подписании документа":
+
[source,pre,codeblock,language-csharp]
----
private void sendReplySignatureRejectionButton_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
  EdiScriptHelper ediScriptHelper = new EdiScriptHelper(CardControl);
  ediScriptHelper.SendReplySignatureRejection();
}
----
* для команды "Запросить аннулирование":
+
[source,pre,codeblock]
----
private void sendRequestRevocation_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
  EdiScriptHelper ediScriptHelper = new EdiScriptHelper(CardControl);
  ediScriptHelper.SendRevocation();
}
----
* для команды "Подтвердить аннулирование":
+
[source,pre,codeblock]
----
private void sendApproveRevocation_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
  EdiScriptHelper ediScriptHelper = new EdiScriptHelper(CardControl);
  ediScriptHelper.SendReplyRevocationSignature();
}
----
* для команды "Отказать в аннулировании":
+
[source,pre,codeblock]
----
private void sendRejectRevocation_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
  EdiScriptHelper ediScriptHelper = new EdiScriptHelper(CardControl);
  ediScriptHelper.SendReplyRevocationRejection();
}
----
. Добавьте в разметку карточки элемент управления *Журнал обмена сообщениями*. Рекомендуется размещать элемент управления на новой вкладке (например, "Журнал обмена ЮЗДО"). Настраивать элемент управления не требуется.

[[concept_ivq_bbt_zz__section_zbx_rn2_gjb]]
=== Настройка разметки вида "Документ/Исходящий"

. Откройте в [.dfn .term]_Конструкторе разметок_ настройки вида [.dfn .term]_Документ/Исходящий_.
. Добавьте на ленту карточки новую группу с названием "Электронный обмен".
. Добавьте в группу "Электронный обмен" команды:
* "Отправка документов",
* "Отправка документов с выбором файлов",
* "Отправка документов с подписанием",
* "Отправка документов с подписанием и выбором файлов",
* "Запросить аннулирование",
* "Подтвердить аннулирование",
* "Отказать в аннулировании".
. Укажите операции доступа для добавленных команд.
. Добавьте в скрипт карточки обработчики для новых команд.
[loweralpha]
.. Добавьте в скрипт карточки ссылку на дополнительную сборку [.ph .filepath]`DocsVision.Edi.DocumentScript.dll`.
.. В раздел подключаемых пространств имен добавьте:
+
[source,pre,codeblock,language-csharp]
----
using DocsVision.Edi.DocumentScript;
----
.. Добавьте обработчики для новых команд:
* для команды "Отправка документов":
+
[source,pre,codeblock,language-csharp]
----
private void sendDocumentButton_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
  if (!CardControl.Save())
    return;

  EdiScriptHelper ediScriptHelper = new EdiScriptHelper(CardControl);
  ediScriptHelper.SendDocument();
}
----
* для команды "Отправка документов с выбором файлов":
+
[source,pre,codeblock,language-csharp]
----
private void sendDocumentFilesButton_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
  if (!CardControl.Save())
    return;
                  
  EdiScriptHelper ediScriptHelper = new EdiScriptHelper(CardControl);
  ediScriptHelper.SendDocumentFiles();
}
----
* для команды "Отправка документов с подписанием":
+
[source,pre,codeblock,language-csharp]
----
private void signAndSendDocumentButton_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
  if (!CardControl.Save())
    return;
                  
  EdiScriptHelper ediScriptHelper = new EdiScriptHelper(CardControl);
  ediScriptHelper.SignAndSendDocument();
}
----
* для команды "Отправка документов с подписанием и выбором файлов":
+
[source,pre,codeblock,language-csharp]
----
private void signAndSendDocumentFilesButton_ItemClick(System.Object sender, DevExpress.XtraBars.ItemClickEventArgs e)
{
  if (!CardControl.Save())
    return;
                  
  EdiScriptHelper ediScriptHelper = new EdiScriptHelper(CardControl);
  ediScriptHelper.SignAndSendDocumentFiles();
}
----
* для команд "Запросить аннулирование", "Подтвердить аннулирование" и "Отказать в аннулировании" скрипты аналогичны скриптам вида "Документ/Входящий" (см. выше).
. Добавьте в разметку карточки элемент управления *Журнал обмена сообщениями*. Рекомендуется размещать элемент управления на новой вкладке (например, "Журнал обмена ЮЗДО"). Настраивать элемент управления не требуется.

[[concept_ivq_bbt_zz__section_cgv_4jf_gjb]]
=== Отображение типа неформализованного документа в карточке

Если требуется, в разметку карточки можно добавить текстовое поле для отображения типа неформализованного документа. Тип неформализованного документа содержится в расширенном поле "Данные УПД/Тип документа" карточки Документ.

[[concept_ivq_bbt_zz__section_cgv_gjb]]
=== Дополнительные функции документа

* Если модуль устанавливался ранее и версия модуля в БД была обновлена до последней, в конструкторе разметок в поле карточки документа [.dfn .term]_Данные УПД / Функция документа_ (`UniversalDocumentData / DocumentFunction`) можно добавить значения `СвРК = 3`, `СвЗК = 4`, это будет соответствовать новым значениям атрибута [.dfn .term]_Функция УПД_.
* Если модуль устанавливается впервые или после обновления была создана новая БД, дополнительных действий не требуется.
