= Настройка обмена пакетами с Диадок

Данное расширение модуля позволяет послать в одном пакете Диадок не только файл УПД или другой структурированный документ, но и связанные с ним неструктурированные документы.

WARNING: Чтобы неструктурированный документ оказался добавлен в пакет, он должен быть связан с УПД ссылкой типа _Связано с (ЮЗДО)_ (см. <<links,"Особенности формирования связей">> ниже).

[#send]
== Отправка пакета

При нажатии кнопки *Подписать* и отправить на форме УПД производятся следующие действия:

. У связанного с УПД неформализованного документа проверяется наличие в поле Контрагент записи соответствующей контрагенту-получателю УПД. Если запись не соответствует или отсутствует, будет выведено сообщение об ошибке и предложено указать контрагента.
. При помощи ЭП подписывается УПД и связанные с ним документы.
. Формируется диалоговое окно с соответствующими изменениями. В окне отображается информация о том, что был сформирован пакет документов.
. По нажатию *ОК* формируется пакет и передается на отправку.
. Также изменяются записи в журнале обмена ЮЗДО карточки УПД. В журнале фиксируется информация о ходе обработки документа УПД и связанных файлов.

[#receive]
== Получение Пакета

Если контрагент переслал пакет включающий УПД и дополнительные неформализованные документы, при получении пакета будут сформированы карточки УПД и приложенных документов с соответствующими связями.

Чтобы подписать полученный УПД со связанными документами, необходимо подписать документ, к которому привязаны остальные ссылками _Ссылается на (ЮЗДО)_. В этом случае пакет будет автоматически сформирован, подписан и отправлен.

При формировании запроса на уточнение, корректировку и исправление УПД, неформализованные документы, входящие в пакет, остаются неизменными.

[#links]
== Особенности формирования связей

.При получении пакетов обрабатываются все возможные варианты связей со следующим приоритетом:
. Если был найден родительский документ, в нём создаётся ссылка на текущий, а в текущий добавляется ссылка на родительский.
. Если был найден документ, подчиненный текущему, в подчинённый добавляется ссылка на родительский (текущий), а в текущем создаётся ссылка на подчинённый.
. Если был найден документ с тем же ID, первый формализованный документ в пакете будет определён как родительский и будут сформированы соответствующие ссылки.

Связанные документы — это всегда ссылка _Ссылается на (ЮЗДО)_. Никакие другие ссылки, включая обратную _Связано с (ЮЗДО)_, аналогичным образом не обрабатываются.

Если требуется работа со ссылками _Ссылается на (ЮЗДО)_ или _Связано с (ЮЗДО)_ в других карточках, необходимо разрешить ее выбор и показывать этот тип ссылки в списке ссылок. Глубина связей для любых обработок составляет всегда только один уровень вниз. Рекурсивный поиск связей не производится.

При подписании пакета учитывается наличие связей, но при этом остаётся возможность подписать любой связанный документ. Можно подписать пакет, в котором уже есть подписанные связанные документы, но родительский документ не подписан. В таком случае будет подписан родительский документ, а также связанные документы, у которых ещё нет подписи. Неподписанные документы будут отображены в сообщении.

[#settings]
== Настройка функций отправки и получения пакетов

В рамках модуля реализована возможность добавить новые функции самостоятельно.

Для отправки пакета из родительского документа и всех связанных требуется вызвать метод:

 EdiScriptHelper.SignAndSendWithLinked();

Вызов метода можно привязать к новой кнопке или заменить прежний вызов метода на требуемой кнопке отправки.

Для подписания пакета, включающего родительский документ и связанные требуется вызвать метод:

 EdiScriptHelper.SendCardWithLinkedReplySignature();

Вызов метода можно привязать к новой кнопке или заменить прежний вызов метода на требуемой кнопке отправки.

