= Процедура обмена неформализованными документами

. Пользователь инициирует функцию отправки неформализованного документа, воспользовавшись командой в карточке Документ.
+
[NOTE]
====
Специалист, осуществляющий настройку модуля, с помощью API модуля и предоставляемой возможности разработки компонентов модуля может реализовать собственный сценарий отправки.
====
. Пользователь определяет параметры отправки (отправляемые файлы, ящик организации и др.) и отправляет документ. При этом будет сформирована _карточка обмена сообщениями_.
+
До подтверждения пользователем отправки _карточка обмена сообщениями_ находиться в статусе "Создается", после -- "Готово к отправке".
+
[NOTE]
====
Все возможные статусы _Карточки обмена сообщениями_ приведены в описании схемы карточки (документ "Описание полей карточек модуля").
====
+
Получателями данного неформализованного документа будут являться контрагенты, указанные в карточке Документ, для которых в _Справочнике настроек операторов ЮДЗО_ определен ящик контрагента. Если данная связь не выявлена (у контрагента нет ящика) -- будет выдано предупреждение.
. _Карточки обмена сообщениями_ со статусом "Готово к отправке" обрабатываются бизнес-процессом "Отправка сообщений ЮЗДО", который формирует по карточкам сообщения электронного обмена и отправляет их оператору ЭДО. Статус отправленных карточек изменяется на "Отправлен контрагенту".
. Оператор ЭДО получает сообщение электронного обмена и передает его контрагенту.
. Контрагент обрабатывает полученный документ и формирует на него ответ (положительный или отрицательный). Также контрагент может передать собственный неформализованный документ.
. Бизнес-процесс "Получение сообщений ЮЗДО" получает электронные сообщения от оператора ЭДО.
. Если входящее сообщение содержит ответ на ранее отправленный неформализованный документ, то статус соответствующей ему _Карточки обмена сообщениями_ будет изменен на одно из значений:
* "Получен отказ от контрагента" -- если от контрагента получен отказ в подписании;
* "Получена подпись от контрагента" -- если от контрагента получено положительное решение по подписанию;
* "Получен запрос на аннулирование" -- если от контрагента получен запрос на аннулирование документа;
* "Аннулирован" -- если от контрагента получено подтверждение запроса на аннулирование документа;
* "Ошибка" -- если при обмене электронными сообщениями с данным неформализованным документом произошли ошибки на стороне {dv}, оператора ЭДО или контрагента.
. Если входящее сообщение содержит новый документ, будет создана карточка входящего документа и соответствующая ей _Карточка обмена сообщениями_.
* Если контрагент запросил подпись -- документ будет создан со статусом "Получен на подпись от контрагента". Пользователь должен будет отправить подпись документа или отказ в подписании.
* Если контрагент не запросил подпись -- документ будет создан со статусом "Получен от контрагента".
. Если входящее сообщение содержит запрос на аннулирование ранее полученного неформализованного документа, статус документа будет изменен на "Получен запрос на аннулирование".
