= Процедура обмена формализованными документами

=== Отправка

. Пользователь инициирует функцию отправки формализованного документа, воспользовавшись командой в карточке исходящего формализованного документа.
. Пользователь выбирает ящик организации и отправляет документ. Если в документе нет ошибок и заполнены все обязательные атрибуты, формируется [.dfn .term]_Карточка обмена сообщениями_.
+
После подтверждения пользователем отправки [.dfn .term]_Карточка обмена сообщениями_ переходит в статус "Готово к отправке". После отправки карточка УПД и статус обмена в журнале обмена карточки ЮЗДО переходят в состояние "Подписан и отправлен".
. [.dfn .term]_Карточки обмена сообщениями_ с состоянием "Готово к отправке" обрабатываются бизнес-процессом "Отправка сообщений ЮЗДО", который формирует по карточкам сообщения электронного обмена и отправляет их оператору ЭДО. Отправленные карточки переводятся в состояние "Отправлен контрагенту".
. Оператор ЭДО получает сообщение электронного обмена и передает контрагенту формализованный документ. По факту получения титула продавца контрагенту и отправителю формализованного документа направляется квитанция.
+
Статус обмена в журнале обмена карточки УПД переходит в "Требуется подтверждение получения".
. Пользователь подтверждает получение квитанции о доставке титула продавца.
+
Статус обмена в журнале обмена карточки УПД переходит в "Отправлен контрагенту".
. Контрагент обрабатывает полученный формализованный документ и формирует ответ, который может содержать:
* титул покупателя,
* отказ в подписи,
* запрос на уточнение.
. Бизнес-процесс "Получение сообщений ЮЗДО" получает электронные сообщения от оператора ЭДО.
. В зависимости от ответа контрагента:
* Если был передан титул покупателя:
[loweralpha]
.. В карточку Исходящего УПД добавляется файл, содержащий титул покупателя.
.. Карточка УПД и статус обмена в журнале обмена карточки УПД переходят в состояние "Получена подпись от контрагента".
* Если был передан отказ в подписи – карточка УПД и статус обмена в журнале обмена карточки УПД переходят в состояние "Получен отказ от контрагента".
* Если был передан запрос на уточнение – статус обмена в журнале обмена карточки УПД переходит в состояние "Требуется подтверждение", после отправки – в "Требуется уточнение".
. Если был получен отказ в подписи, работа с данным документом прекращается.
. Если был передан запрос на уточнение – пользователь формирует Корректировочный УПД или Исправление УПД.

=== Получение

. Бизнес-процесс "Получение сообщений ЮЗДО" получает электронные сообщения от оператора ЭДО.
+
По формализованным документам формируются карточки соответствующих видов со статусом обмена "Получен от контрагента"/"Получен на подпись от контрагента".
. По полученным УПД, исправление УПД, корректировка УПД, счёта-фактура, исправление счета-фактуры и корректировка счета фактуры со статусом "Требуется подтверждение получения" пользователь должен отправить подтверждение получения извещения.
+
После получения подтверждения оператор ЭДО отправит извещение о получении подтверждения, получение которого также должно быть подтверждено пользователем.
. Для полученных накладных и акта пользователь может запросить аннулирование – статус обмена сменится на "Отправлен запрос на аннулирование".
. Для полученных счёта-фактуры, исправления счета-фактуры и корректировки счета фактуры пользователь может:
* запросить аннулирование – статус обмена сменится на "Отправлен запрос на аннулирование";
* запросить уточнение – статус обмена сменится на "Отправлен запрос на уточнение".
. Для полученных УПД, исправление УПД и корректировка УПД пользователь может:
* подписать документ – статус обмена сменится на "Отправлена ответная подпись контрагенту", работа с данным документом прекращается;
* отказать в подписании – статус обмена сменится на "Отправлен отказ от подписи контрагенту";
* запросить уточнение – статус обмена сменится на "Отправлен запрос на уточнение".
. После подписания документа, пользователь может отправить запрос на аннулирование. Статус обмена сменится на "Отправлен запрос на аннулирование", возможность выполнения других операций с документом – заблокирована.
+
Контрагент может аннулировать документ в одностороннем порядке:

* для Акта и Накладной – до подписания;
* для остальных формализованных видов – до отправки первого извещения.
+
При одностороннем аннулировании документ сразу переходит в статус "Аннулирован", работа с данным документом прекращается.
. Если был отправлен запрос на аннулирование:
* при отказе в аннулировании со стороны контрагента – статус обмена вернётся в:
** "Получен от контрагента" – для счёта-фактуры, исправления счета-фактуры и корректировки счета фактуры;
** "Отправлена ответная подпись контрагенту" – для УПД, исправление УПД, корректировка УПД, накладная и акт;
* при подтверждении аннулирования – статус обмена сменится на "Аннулирован", работа с данным документом прекращается.
. Если был отправлен запрос на уточнение:
* если документ был подписан или подписание не требуется – пользователь может отправить запрос на аннулирование;
* если документ не был подписан – работа с данным документом прекращается.
. Если был получен запрос на аннулирование от контрагента, статус обмена сменится на "Получен запрос на аннулирование".
+
Пользователь может:

* подтвердить аннулирование – статус обмена сменится на "Аннулирован", работа с данным документом прекращается.
* отказать в аннулировании – статус обмена вернётся в предыдущее значение ("Получен от контрагента", "Получен на подпись от контрагента" или "Отправлена ответная подпись контрагенту").
