= Настройка функций обмена приглашениями ЭДО

Для работы с формализованными документами предназначены карточки подвидов _Документ/УПД_:

. Исходящее приглашение ЭДО.
. Входящее приглашение ЭДО.

Указанные виды карточек предоставляются с настроенными разметками, автоматом состояний и ролевой моделью.

.Администратору необходимо:
. Добавить виртуальные папки для работы с УПД.

[#formalized-folders]
== Настройка папок для приглашений ЭДО

Для удобства работы с приглашениями ЭДО можно добавить пользователям модуля виртуальные папки со следующими поисковыми запросами:

* _Журнал Все приглашения_ -- возвращает все виды приглашений во всех статусах.
* _Журнал Исходящие приглашения_ -- возвращает только исходящие приглашения во всех статусах.
* _Журнал Входящие приглашения_ -- возвращает только входящие приглашения во всех статусах.
* _Поиск Приглашений_ -- выполняет поиск приглашений по различным полям.

В настройках данных папок рекомендуется установить представление по умолчанию -- _Приглашения ЭДО (Все)_.

Поисковые запросы и представления для папок входящих приглашений ЭДО, если требуется, могут быть разработаны самостоятельно.

