= Настройка функций обмена приглашениями ЭДО

// tag::work-with[]
WARNING: Работа с приглашениями по умолчанию производится только из {wc}а. Для работы с приглашениями через {wincl} администратор должен самостоятельно настроить разметки.
// end::work-with[]

Для работы с формализованными документами предназначены карточки подвидов _Документ/УПД_:

. Исходящее приглашение ЭДО.
. Входящее приглашение ЭДО.

Указанные виды карточек предоставляются с настроенными разметками, автоматом состояний и ролевой моделью.

.Администратору необходимо:
. Добавить виртуальные папки для работы с УПД.

[#folders]
== Настройка папок для приглашений ЭДО

Для удобства работы с приглашениями ЭДО можно добавить пользователям модуля виртуальные папки со следующими поисковыми запросами:

* _Журнал Все приглашения_ -- возвращает все виды приглашений во всех статусах.
* _Журнал Исходящие приглашения_ -- возвращает только исходящие приглашения во всех статусах.
* _Журнал Входящие приглашения_ -- возвращает только входящие приглашения во всех статусах.
* _Поиск Приглашений_ -- выполняет поиск приглашений по различным полям.

В настройках данных папок рекомендуется установить представление по умолчанию -- _Приглашения ЭДО (Все)_.

Поисковые запросы и представления для папок входящих приглашений ЭДО, если требуется, могут быть разработаны самостоятельно.

[#layout]
== Настройка разметки вида "Входящее приглашение ЭДО"

. Откройте в _Конструкторе разметок_ настройки вида _Документ/Исходящий_.
. Добавьте на ленту карточки новую группу с названием _Электронный обмен_.
. Добавьте в группу _Электронный обмен_ команды:
+
* *Отправить* приглашение.
* *Отозвать* приглашение.
* *Принять* приглашение.
* *Отказать* в принятии приглашения.
+
. Укажите операции доступа для добавленных команд.
. Добавьте в скрипт карточки обработчики для новых команд.
.. Добавьте в скрипт карточки ссылку на дополнительную сборку `DocsVision.Edi.DocumentScript.dll`.
.. В раздел подключаемых пространств имен добавьте:
+
[source,csharp]
----
using DocsVision.Edi.EdiScriptHelpers;
----
+
.. Добавьте обработчики для новых команд:
+
.Для команды _Отправить_ приглашение:
[source,csharp]
----
public bool SendInvitation()
----
+
.Для команды _Отозвать_ приглашение:
[source,csharp]
----
public bool CancelInvitation()
----
+
.Для команды _Принять_ приглашение:
[source,csharp]
----
public bool AcceptInvitation()
----
+
.Для команды _Отказать_ в принятии приглашения:
[source,csharp]
----
public bool RejectInvitation()
----
+
. Добавьте в разметку карточки элемент управления _Журнал работы с приглашениями_. Рекомендуется размещать элемент управления на новой вкладке (например, _Журнал работы с приглашениями БЗДО_). Настраивать элемент управления не требуется.
. Загрузите БП для обмена приглашениями:
+
* `CardPackage\ReceiveEdiInvitations.xml` -- для получения входящих приглашений к обмену.
* `CardPackage\SendEdiInvitations.xml` -- для отправки исходящих приглашений к обмену.

[#layouts]
== Настройки web-разметок

Для работы с приглашениями ЭДО в разметках {wc}а предназначены следующие обработчики событий:

.События и обработчики событий исходящих приглашений:
* Для кнопки *Отправить* необходимо назначить имя `ediSignAndSendButton`
* Для кнопки *Отозвать* необходимо назначить имя `ediRecallButton`
* `edi_OutgoingInvitation_cancelClick` -- событие нажатия на кнопку *Отозвать*.
* `edi_OutgoingInvitation_signAndSendClick` -- событие нажатия на кнопку -- *Подписать и отправить*.
** Событие требует заполнения поля `Contract.PartnerCompany` -- организация контрагента, получатель приглашения. Это единственное обязательно поле в карточке входящего и исходящего приглашения.
* `edi_OutgoingInvitation_cardOpening` -- перед открытием карточки.
* `edi_OutgoingInvitation_cardOpened` -- после открытия карточки.

Кнопка *Отправить* доступна только если ещё приглашение не было отправлено ранее. Для повторной отправки потребуется создать новую карточку.
Кнопка *Отозвать* доступна только если приглашение было утверждено.

.События и обработчики событий входящих приглашений:
edi_IncomingInvitation_cardOpening - перед открытием карточки
edi_IncomingInvitation_cardOpened - после открытия карточки
--- кнопка "Принять" должна иметь имя ediAcceptInvitationButton
--- кнопка "Отклонить" должна иметь имя ediDeclineInvitationButton
edi_IncomingInvitation_acceptInvitationClick - Событие клика по кнопке - Принять
edi_IncomingInvitation_declineInvitationClick - Событие клика по кнопке - Отклонить




