= Карточки Docsvision для работы с формализованными документами

Для работы с формализованными документами в Модуле предусмотрено несколько специальных видов карточек, производных от вида [.dfn .term]_Документ_:

* Исходящий УПД – предназначен для создания исходящих УПД;
** Исходящий УКД – предназначен для создания корректировок к отправленным УПД;
** Исходящее исправление УПД – предназначен для формирования исправлений отправленных УПД;
*** Исходящее исправление УПД (820) – предназначен для формирования исправлений для отправленных УПД в формате, вступающем в силу в 2020 году;
** Исходящий УПД (820) – предназначен для создания исходящих УПД в формате, вступающем в силу в 2020 году;
* Входящий УПД – предназначен для работы с входящими УПД. Карточки данного вида создаются Модулем при получении формализованных документов.
** Входящий УКД – предназначен для работы с корректировками полученных УПД;
** Входящий УПД (820) – предназначен для работы с корректировками полученных УПД в формате, вступающем в силу в 2020 году;
** Формализованный акт – предназначен для работы с входящими актами и формализованными накладными в рекомендованном ФНС формате;
*** Формализованный акт (820) – предназначен для работы с входящими актами и формализованными накладными в рекомендованном ФНС формате, вступающем в силу в 2020 году.

