= Работа с исходящими документами

Работа с исходящими документами включает следующие этапы:

. Пользователь Модуля (далее – Продавец) создает исходящий документ вида (или подвида) [.dfn .term]_Исходящий УПД_ и отправляет его контрагенту (далее – Покупатель).
. Оператор ЭДО принимает документ от Продавца и отправляет ему Извещение о получении, а также передаёт документ Покупателю.
. Продавец получает Извещение о получении от оператора ЭДО и подтверждает его получение. Подтверждение не требуется для актов и накладных.
. После получения документа Покупатель может:
* подписать или отказать в подписании документа – не требуется для счёт-фактуры;
* запросить аннулирование – для счёт-фактуры;
* запросить уточнение у Продавца.
. Продавец получает ответ от Покупателя.
* Если Покупатель подписал документ (был сформирован титул покупателя):
[loweralpha]
.. Титул покупателя добавляется в карточку [.dfn .term]_Исходящего УПД_ (или подвида).
.. Карточка и статус обмена переходят в состояние "Получена подпись от контрагента".
.. Документооборот завершен.
* Если Покупатель отказал в подписании документа, карточка и статус обмена переходят в состояние "Получен отказ от контрагента".
* Если Покупатель запросил уточнение, статус обмена переходит в состояние "Требуется подтверждение получения", а далее в "Требуется уточнение". После этого работа с данным документом завершается. Пользователь Модуля может создать корректировочный УПД или исправление УПД.
. Покупатель или Продавец могут запросить аннулирование подписанного документа. Вторая сторона ЭДО может подтвердить или отказать в аннулировании.
+
Если Продавец запросил аннулирование до получения извещения от оператора ЭДО (о получении документа от Продавца), документ будет аннулирован в одностороннем порядке (без подтверждения со стороны Покупателя).
