= Изменения в релизной версии

== Функциональные изменения

Отображение ИНН и КПП отдельной колонкой::
В справочнике настроек операторов ЮЗДО в {wincl}е, на вкладках _Контрагенты_ и _Организации_ добавлены новые колонки для отображения ИНН и КПП.
+
Чтобы после обновления модуля отображались корректные данные, выполните повторную загрузку организаций в справочник.
+
Изменение добавляет новые поля  и не затрагивает существующие привязки.

Новые виды документов::
Добавлены два новых вида документов: *Входящий УКД (736)* и *Исходящий УКД (736)* в соответствии с изменениями о прекращении поддержки старого формата УКД.

Дополнительные функции документа::
Добавлены новые функции документа `СвРК = 3` и `СвЗК = 4`.
+
Если модуль устанавливался ранее в поле карточки документа *Данные УПД / Функция документа* (`UniversalDocumentData/DocumentFunction`) можно добавить новые значения.
+
Если модуль устанавливается впервые или после обновления была создана новая БД, дополнительных действий не требуется.
