= Изменения в релизной версии

МЧД при обмене документами::
Добавлена возможность использовать МЧД при обмене документами через Диадок.

Создание МЧД через оператора ЭДО::
Добавлена возможность создать или отозвать (отвязать от оператора) доверенность через оператора МЧД. Добавлена возможность просматривать МЧД в журнале подписей.

Использование МЧД при отправке и получении документов::
Добавлена возможность использовать МЧД при отправке и получении документов через оператора Диадок при работе в Web-клиенте.

Новые опции лицензии::
Добавлена опция лицензии для использования МЧД с модулем ЭДО в Web-клиенте: "Модуль интеграции с реестром МЧД". Лицензия требуется при передаче на регистрацию и отправке МЧД.

Плагин "Журнала обмена МЧД"::
Разработан плагин `POAMessagesLog`, формирующий таблицу _Журнала обмена МЧД_. Для настройки собственных решений плагин может быть добавлен в свойство `*Название плагина*` элемента управления `_Контрол табличных данных_`.

Выбор МЧД при подписании::
В стандартные диалоги подписания Windows-клиента добавлена возможность выбора МЧД. В окно _Выбор сертификата_ добавлена область _Использовать доверенность_, позволяющая подписать документ с использованием МЧД, если для сотрудника подобрана доверенность.

Экспорт МЧД::
Если при подписании в Windows-клиенте использовалась МЧД, она может быть экспортирована вместе с ЭП. Экспорт МЧД регулируется настройкой в меню экспорта и отправки по Email, флаг `*Экспорт МЧД (при наличии) к электронной подписи*`.

Информация об МЧД в журнале ЭП::
В журнале ЭП Windows-клиента отображается информация об использованной при подписании МЧД:
+
* Номер доверенности.
* Доверитель.
* Подписант.
* Представитель.
* Полномочия: поля Код полномочий и Название полномочий из Справочника полномочий или свободное текстовое описание.
* Дата совершения доверенности.
* Срок действия доверенности.
* Статус доверенности: подготовка, действует, отозвана (с указанием даты отзыва).
* Формат доверенности.
* Найденные несоответствия -- отображается, если были найдены несоответствия.

Отправка МЧД в распределённый реестр через оператора ЭДО::
Добавлена возможность отправки МЧД в распределённый реестр ФНС после подписания при наличии лицензии. Потребуется наличие лицензии "Модуль интеграции с реестром МЧД" и замена скрипта кнопки.

== Изменения в API

Методы отправки и получения документов с МЧД::
Разработаны методы API отправки и получения документов из Диадок для работы с МЧД.
