= Изменения в релизной версии

== Функциональные изменения

Расширения для работы в {wc}е::
В инсталлятор модуля добавлены компоненты для работы из {wc}а. Для работы с ЭДО в {wc}е требуются также дополнительные компоненты модуля {wc} (_Компоненты модуля интеграции с операторами ЭДО_).
+
WARNING: Работа с модулем ЭДО поддерживается только в {wc} версии {wc-req} и выше. Работа в модуле {wc} версии 5.5.17 в данный момент не поддерживается.

Разметки для {wc}а::
Модуль приносит web-разметки для работы с документами: Входящий и Исходящий УПД и Входящие и Исходящие Приглашения ЭДО.

Приглашения к обмену::
Добавлена возможность работать с приглашениями ЭДО. Приглашения к обмену используются, чтобы предложить контрагенту перейти на электронный документооборот.

Новые БП::
В модуль добавлены новые БП для работы с Приглашениями к обмену ЭДО:
+
* БП _Отправка приглашений ЭДО_.
* БП _Получение приглашений ЭДО_.

Новые преобразования::
В модуль добавлены новые преобразования:
* `UniInvoiceFields.xslt` -- шаблон преобразования для УПД.
* `UniInvoiceCorrFields.xslt` -- шаблон преобразования для УКД.
* `UniInvoiceTorgRu.xslt` -- шаблон преобразования для Товарной накладной ТОРГ-12.
* `UniInvoiceSF.xslt` -- шаблон преобразования для Счета-фактуры.
* `UniInvoiceAct.ru.xslt` -- шаблон преобразования для Формализованного акта.

[#company]
Выбор организации при отправке::
В диалоги отправки исходящих документов добавлена возможность выбора организации или подразделения (раньше можно было выбрать только подразделение).

Отображение ИНН и КПП отдельной колонкой::
В справочнике настроек операторов ЮЗДО в {wincl}е, на вкладках _Контрагенты_ и _Организации_ добавлены новые колонки для отображения ИНН и КПП.
+
Чтобы после обновления модуля отображались корректные данные, выполните повторную загрузку организаций в справочник.
+
Изменение добавляет новые поля  и не затрагивает существующие привязки.

Новые виды документов::
Добавлены два новых вида документов: *Входящий УКД (736)* и *Исходящий УКД (736)* в соответствии с изменениями о прекращении поддержки старого формата УКД.

Дополнительные функции документа::
Добавлены новые функции документа `СвРК = 3` и `СвЗК = 4`.
+
Если модуль устанавливался ранее в поле карточки документа *Данные УПД / Функция документа* (`UniversalDocumentData/DocumentFunction`) можно добавить новые значения.
+
Если модуль устанавливается впервые или после обновления была создана новая БД, дополнительных действий не требуется.

[#api]
== Изменения в API

* Добавлен новый интерфейс `IImportService2` для реализации постраничной загрузки контрагентов.
* Описан класс `xref:programmer:api/BoxesService.adoc[BoxesService]` для выполнения стандартных операций.
+
.Класс дополнен новыми методами:
** `ImportPartner(OperatorsOperator, string, string)` -- импортирует одного контрагента по ИНН и КПП.
** `ImportPartner(OperatorsOperator, PartnersCompany)` -- импортирует одного контрагента по организации контрагента.
** `ProcessAllNewInvitations(ILogWriter)` -- находит и обрабатывает все новые входящие приглашения.
** `ProcessAllNewInvitationsToSend(ILogWriter)` -- находит и обрабатывает все новые исходящие приглашения.
** `CheckInvitationsStatus(ILogWriter, DateTime?)` -- проверяет статус приглашений с указанной даты.
* Добавлены xref:programmer:api/web-server-methods.adoc[методы] для серверного и клиентского расширения {wc}а.
* Добавлено описание для следующих классов:
** `xref:programmer:api/DataReaderService.adoc[DataReaderService]`
** `xref:programmer:api/DocumentUpdaterService.adoc[DocumentUpdaterService]`
** `xref:programmer:api/InvitationService.adoc[InvitationService]`
** `xref:programmer:api/LoaderService.adoc[LoaderService]`
** `xref:programmer:api/OutgoingMessagesService.adoc[OutgoingMessagesService]`
